#include "Core.h"

#include <d3d8.h>

const char* HRESULT_TO_STRING(HRESULT hr)
{
#define _HRESULT_TO_STRING(_hr) if(hr == _hr) return #_hr;
	_HRESULT_TO_STRING(D3DERR_WRONGTEXTUREFORMAT);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDCOLOROPERATION);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDCOLORARG);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDALPHAOPERATION);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDALPHAARG);
	_HRESULT_TO_STRING(D3DERR_TOOMANYOPERATIONS);
	_HRESULT_TO_STRING(D3DERR_CONFLICTINGTEXTUREFILTER);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDFACTORVALUE);
	_HRESULT_TO_STRING(D3DERR_CONFLICTINGRENDERSTATE);
	_HRESULT_TO_STRING(D3DERR_UNSUPPORTEDTEXTUREFILTER);
	_HRESULT_TO_STRING(D3DERR_CONFLICTINGTEXTUREPALETTE);
	_HRESULT_TO_STRING(D3DERR_DRIVERINTERNALERROR);
	_HRESULT_TO_STRING(D3DERR_NOTFOUND);
	_HRESULT_TO_STRING(D3DERR_MOREDATA);
	_HRESULT_TO_STRING(D3DERR_DEVICELOST);
	_HRESULT_TO_STRING(D3DERR_DEVICENOTRESET);
	_HRESULT_TO_STRING(D3DERR_NOTAVAILABLE);
	_HRESULT_TO_STRING(D3DERR_OUTOFVIDEOMEMORY);
	_HRESULT_TO_STRING(D3DERR_INVALIDDEVICE);
	_HRESULT_TO_STRING(D3DERR_INVALIDCALL);
	_HRESULT_TO_STRING(D3DERR_DRIVERINVALIDCALL);

	_HRESULT_TO_STRING(NOERROR);
	_HRESULT_TO_STRING(E_UNEXPECTED);
	_HRESULT_TO_STRING(E_NOTIMPL);
	_HRESULT_TO_STRING(E_OUTOFMEMORY);
	_HRESULT_TO_STRING(E_INVALIDARG);
	_HRESULT_TO_STRING(E_NOINTERFACE);
	_HRESULT_TO_STRING(E_POINTER);
	_HRESULT_TO_STRING(E_HANDLE);
	_HRESULT_TO_STRING(E_ABORT);
	_HRESULT_TO_STRING(E_FAIL);
	_HRESULT_TO_STRING(E_ACCESSDENIED);

	// _HRESULT_TO_STRING(D3DXERR_INVALIDMESH);
	// _HRESULT_TO_STRING(D3DXERR_CANNOTATTRSORT);
	// _HRESULT_TO_STRING(D3DXERR_SKINNINGNOTSUPPORTED);
	// _HRESULT_TO_STRING(D3DXERR_TOOMANYINFLUENCES);
	// _HRESULT_TO_STRING(D3DXERR_INVALIDDATA);
	// _HRESULT_TO_STRING(D3DXERR_LOADEDMESHASNODATA);
#undef _HRESULT_TO_STRING

	const char* unrecognised_error = TEMPSTR("Unrecognized error: 0x%X", static_cast<uint32_t>(hr));
	return unrecognised_error;
}
